= Storing energy using a pile of stones

The world is in dire need of ways to store energy in an sustainable and
economical way. This is particularly true for wind energy which has huge
variations in production often in time-scale of weeks.

The idea of using stones is not new but I believe that the key is to
focus on low-tech solution that takes use of the scaling laws of heat transfer
in an optimal way. This could ideally happen in Finland where there is lot of
empty space and plenty of stones. 

For simply storing heat water is of course ideal solution. Here the hope is
that when using hot stones we could use the energy also to produce
electricity alongside.

I've trying to push this idea forward now and then number of years.
Either the idea is bad or the right people have not been contacted.
As this is not my main profession there is a big risk that the idea
in fact is bad. However, with that risk in mind I thought I would try
the open source approach to see whether it could fly. 

