= Storing energy using a pile of stones

The world is in dire need of ways to store energy in an sustainable and
economical way. This is particularly true for wind energy which has huge
variations in production often in time-scale of weeks.

The idea of using stones is not new [1,2] but I believe that the key is to
focus on really low-tech solution that takes use of the scaling laws of heat transfer
in an optimal way. This could ideally happen in Finland where there is lot of
empty space and plenty of stones. 

For simply storing heat water is of course ideal solution. Here the hope is
that when using hot stones we could use the energy also to produce
electricity alongside.

I've trying to get people interested in the idea for already a few years. 
Either the idea is bad or the right people have not been contacted.
As I lack knowhow in some key technologies (e.g. heat exchangers) here
there is a big risk that the idea
in fact is really bad. However, with that risk in mind I thought I would try
the open source approach to see whether it could fly. 

This is a open call to produce information, models, drawings, ideas, computaions etc. in this repo. I will try to contribute myself too. I have background
in physics and I handle basic heat transfer, but turbulent CFD and
existing technologies in heat exchangers and beyond is not really my cup of tea. If we would get together a group of people with complementary expertise we
better determine the potential of this idea. 



## References

https://cleantechnica.com/2019/03/19/storing-energy-by-heating-stones-to-600-degrees-could-power-whole-country-for-hours/

https://www.niras.com/projects/innovative-energy-storage/

https://www.theengineer.co.uk/content/news/hot-rocks-offer-solution-to-grid-scale-energy-storage